name: Yad2 Scraper

on:
  schedule:
    - cron: '*/15 3-17 * * *'
    - cron: '*/15 18-20 * * *'
  workflow_dispatch:
    branches:
      - '**'

jobs:
  scraper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Install packages
        run: yarn install --ignore-engines

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "${{ secrets.GIT_CONFIG_EMAIL }}"

      - name: Run scraper
        id: scraper_run
        run: |
          export TELEGRAM_API_TOKEN=${{ secrets.TELEGRAM_API_TOKEN }}
          export TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}
          export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
          export PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
          yarn scrape
          if [ $? -ne 0 ]; then
            echo "Scraper failed!"
            exit 1
          fi

      - name: Push new json data if needed
        run: |
          if [ -f ./push_me ]; then
            echo "Pushing to GitHub..."
            git add data/*.json 
            DATE=$(TZ=':Asia/Jerusalem' date +"%F %H:%M:%S")
            git commit -m "updated data - $DATE"
            git push
          fi
