name: Yad2 Scraper

on:
  schedule:
    - cron: '*/15 3-17 * * *'
    - cron: '*/15 18-20 * * *'
  workflow_dispatch:
    branches:
      - '**'

jobs:
  scraper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure we fetch all history

      - name: Install chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Install packages
        run: yarn install

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "${{ secrets.GIT_CONFIG_EMAIL }}"

      - name: Run scraper
        id: scraper_run
        run: |
          export TELEGRAM_API_TOKEN=${{ secrets.TELEGRAM_API_TOKEN }}
          export TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}
          export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
          export PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
          yarn scrape
          if [ $? -ne 0 ]; then
            echo "Scraper failed!"
            exit 1
          fi
          echo "::set-output name=has_new_data::true" # Always set to true, the logic is now in the js
          echo "SCRAPER_OUTPUT=true" >> $GITHUB_OUTPUT # Debug

      - name: Push new json data
        run: |
          echo "Pushing to GitHub..."
          git add data/*.json 
          DATE=$(date +"%F, %H:%M:%S")
          git commit -m "updated data - $DATE"
          git push

